from fpdf import FPDF
import os
from datetime import datetime
import webbrowser
import json

class ASDReportPDF(FPDF):
    def header(self):
        # Slate background for header
        self.set_fill_color(15, 23, 42) # #0F172A
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(225, 29, 72) # #E11D48 (Crimson)
        self.set_xy(10, 15)
        self.cell(0, 10, 'Early Screen ASD', 0, 0, 'L')
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(148, 163, 184) # #94A3B8 (Slate 400)
        self.set_xy(140, 15)
        self.multi_cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d')}\nReport ID: ASD-{(datetime.now()).strftime('%Y%m%d')}-01", 0, 'R')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, 'Confidential Behavioral Screening Report - Generated by Early Screen ASD', 0, 0, 'C')

def generate_pdf_report(results, output_path):
    """Generates a professional PDF report using fpdf2."""
    pdf = ASDReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ── Screening Verdict Section ──
    pdf.set_y(50)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(15, 23, 42) # Slate 900
    pdf.cell(0, 10, "SCREENING VERDICT", 0, 1, 'L')
    
    is_conclusive = results.get('is_conclusive', False)
    dominant_id = results.get('dominant_behavior', 'Unknown')
    verdict_text = "NORMAL ACTIVITY DETECTED" if dominant_id == "Normal" else ("CONCLUSIVE DETECTION" if is_conclusive else "LOW CONFIDENCE / INCONCLUSIVE")
    
    # Emerald vs Amber/Crimson
    if dominant_id == "Normal":
        v_color = (16, 185, 129) # Emerald Green
    elif is_conclusive:
        v_color = (16, 185, 129) # Emerald (for strong MSB as well)
    else:
        v_color = (245, 158, 11) # Amber
    
    pdf.set_fill_color(248, 250, 252) # Slate 50
    pdf.set_draw_color(225, 29, 72) # Crimson
    pdf.rect(10, 60, 190, 30, 'DF')
    
    pdf.set_xy(15, 65)
    pdf.set_font('Helvetica', 'B', 18)
    pdf.set_text_color(*v_color)
    pdf.cell(0, 10, verdict_text, 0, 1, 'C')
    
    dominant = results.get('dominant_behavior_label', results.get('dominant_behavior', 'Unknown'))
    conf = results.get('model_confidence', 0.0)
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(30, 41, 59) # Slate 800
    pdf.cell(0, 10, f"Detected Trait: {dominant} ({conf*100:.1f}%)", 0, 1, 'C')
    
    # ── MSB Trait Analysis Section ──
    pdf.ln(15)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "MSB TRAIT BREAKDOWN", 0, 1, 'L')
    
    vote_shares = results.get('behavior_percentages', {})
    for trait, pct in vote_shares.items():
        if trait.startswith('_'): continue # Skip metadata
        trait_lbl = trait.replace('_', ' ').title()
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(51, 65, 85) # Slate 700
        pdf.cell(50, 8, trait_lbl, 0, 0)
        
        # Draw bar
        start_x = 60
        max_bar_w = 110
        pdf.set_fill_color(241, 245, 249) # Slate 100
        pdf.rect(start_x, pdf.get_y()+2, max_bar_w, 4, 'F')
        
        # Color bar based on trait (Green for Normal)
        if trait_lbl.lower() == "normal":
            pdf.set_fill_color(16, 185, 129) # Emerald
        else:
            pdf.set_fill_color(225, 29, 72) # Crimson
            
        pdf.rect(start_x, pdf.get_y()+2, max_bar_w * (pct/100.0 if pct > 1.0 else pct), 4, 'F')
        
        pdf.set_x(start_x + max_bar_w + 5)
        pdf.set_text_color(225, 29, 72) if trait_lbl.lower() != "normal" else pdf.set_text_color(16, 185, 129)
        val = pct if pct > 1.0 else pct * 100.0
        pdf.cell(20, 8, f"{val:.1f}%", 0, 1, 'R')
    
    # ── Detailed Analysis Description ──
    pdf.ln(10)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "ANALYSIS SUMMARY", 0, 1, 'L')
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(71, 85, 105) # Slate 600
    summary_text = (
        "This report is generated using spatio-temporal deep learning patterns. "
        "The system utilizes a 50% overlapping stride analysis to ensure high precision in identifying "
        "repetitive motor stereotypies. The results provided are objective screening indicators and "
        "should be used to support clinical decision-making by qualified pediatric specialists."
    )
    pdf.multi_cell(0, 5, summary_text)
    
    # ── Technical Specs ──
    pdf.ln(5)
    pdf.set_fill_color(248, 250, 252)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(0, 8, "  TECHNICAL SPECIFICATIONS", 0, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 8)
    pdf.cell(95, 6, "  Analysis Backbone:", 0, 0)
    pdf.cell(95, 6, "ResNet18 + TCN", 0, 1, 'R')
    pdf.cell(95, 6, "  Temporal Stride:", 0, 0)
    pdf.cell(95, 6, "5 Frames (50% Overlap)", 0, 1, 'R')
    pdf.cell(95, 6, "  Source File:", 0, 0)
    pdf.cell(95, 6, os.path.basename(results.get('file_path', 'unknown')), 0, 1, 'R')

    pdf.output(output_path)
    return output_path

def generate_html_report(results, output_path):
    """
    Generates a premium Slate & Crimson HTML report for ASD screening results.
    """
    BG_COLOR = "#0F172A"
    CARD_BG = "#1E293B"
    PRIMARY_TEXT = "#F8FAFC"
    SECONDARY_TEXT = "#94A3B8"
    ACCENT_COLOR = "#E11D48"
    BORDER_COLOR = "#334155"
    SUCCESS_COLOR = "#10B981"
    
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    dominant = results.get('dominant_behavior_label', results.get('dominant_behavior', 'Unknown'))
    confidence = results.get('model_confidence', 0.0)
    vote_shares = results.get('behavior_percentages', {})
    is_conclusive = results.get('is_conclusive', False)
    
    dominant_id = results.get('dominant_behavior', 'Unknown')
    verdict_text = "NORMAL ACTIVITY DETECTED" if dominant_id == "Normal" else ("CONCLUSIVE DETECTION" if is_conclusive else "LOW CONFIDENCE / INCONCLUSIVE")
    verdict_color = SUCCESS_COLOR if (is_conclusive or dominant_id == "Normal") else "#F59E0B"
    
    progress_html = ""
    for trait, pct in vote_shares.items():
        if trait.startswith('_'): continue # Skip metadata
        trait_name = trait.replace('_', ' ').replace('Normal', 'Normal Activity').title()
        fill_color = SUCCESS_COLOR if "Normal" in trait_name else ACCENT_COLOR
        val = pct if pct > 1.0 else pct * 100.0
        progress_html += f"""
        <div class="trait-row">
            <div class="trait-label">{trait_name}</div>
            <div class="bar-container">
                <div class="bar-fill" style="width: {val:.1f}%; background: {fill_color};"></div>
            </div>
            <div class="trait-pct" style="color: {fill_color};">{val:.1f}%</div>
        </div>
        """

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Early Screen ASD - Report</title>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body {{ font-family: 'Inter', sans-serif; background-color: {BG_COLOR}; color: {PRIMARY_TEXT}; margin: 0; padding: 40px; }}
            .container {{ max-width: 800px; margin: 0 auto; background: {CARD_BG}; padding: 40px; border-radius: 12px; border: 1px solid {BORDER_COLOR}; }}
            header {{ border-bottom: 2px solid {ACCENT_COLOR}; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; }}
            .logo {{ font-size: 24px; font-weight: 700; color: {ACCENT_COLOR}; }}
            .verdict-box {{ background: rgba(225, 29, 72, 0.1); border: 1px solid {ACCENT_COLOR}; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 30px; }}
            .verdict-value {{ font-size: 32px; font-weight: 700; color: {verdict_color}; }}
            .trait-row {{ display: flex; align-items: center; margin-bottom: 12px; }}
            .trait-label {{ width: 150px; font-weight: 600; }}
            .bar-container {{ flex-grow: 1; height: 12px; background: {BORDER_COLOR}; border-radius: 6px; overflow: hidden; margin: 0 15px; }}
            .bar-fill {{ height: 100%; border-radius: 6px; }}
            .trait-pct {{ width: 60px; text-align: right; font-weight: 700; color: {ACCENT_COLOR}; }}
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <div class="logo">🧠 Early Screen ASD</div>
                <div style="text-align: right; color: {SECONDARY_TEXT};">Date: {date_str}</div>
            </header>
            <div class="verdict-box">
                <div style="text-transform: uppercase; font-size: 10px; color: {SECONDARY_TEXT}; margin-bottom: 5px;">Screening Verdict</div>
                <div class="verdict-value">{verdict_text}</div>
                <div style="margin-top: 10px; font-size: 18px;">{dominant} ({confidence*100:.1f}%)</div>
            </div>
            <section>
                <h2>MSB Trait Analysis</h2>
                {progress_html}
            </section>
        </div>
    </body>
    </html>
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    return output_path
